name: sick-fits

services:
- name: frontend
  github:
    repo: wesbos/advanced-react-rerecord
    branch: master
    deploy_on_push: true
  source_dir: finished-files/frontend
  routes:
  - path: /
  build_command: npm run build
  run_command: npm start
- name: backend
  github:
    repo: wesbos/advanced-react-rerecord
    branch: master
    deploy_on_push: true
  source_dir: finished-files/backend
  routes:
  - path: /admin
  http_port: 8888
  build_command: npm run build
  run_command: npm start
